#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

skip_commits:
  message: /\[skip (ci|AppVeyor)\]/  # Regex for matching commit message

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
  - Visual Studio 2017
  - Visual Studio 2015

environment:
  global:
    DOCFX_SOURCE_BRANCH_NAME: $APPVEYOR_REPO_BRANCH

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\v3-cache'  # NuGet v3

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - appveyor-retry nuget restore

build:
  parallel: true
  project: SsmlLibraries.sln
  publish_wap: true               # package Web Application Projects (WAP) for Web Deploy
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe SsmlLib.Tests\bin\Release\SsmlLib.Tests.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing entire folder as a zip archive
  - path: SsmlLib

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
- provider: Email
  to:
    - kelton.karboviak@gmail.com
  subject: 'AppVeyor - Build {{status}}'
  message: "{{message}}, {{commitId}}"
  on_build_status_changed: true
